### ISSUE TITLE
Import and georeference drawings

### ISSUE THREAD

**Issue by thomstarnes** [patrickbwarren/qgis-survex-import#5]
I want to be able to get the drawing (i.e. cave walls and features) into QGIS as vector data.

Take a drawing (e.g. from Pocket Topo) and import into QGIS as a geoTIFF. Ideally the survey stations can be used to georeference the image. The drawing can then be traced using QGIS digitising tools.

Not sure on my terminology; please correct as appropriate.

**Comment by patrickbwarren** [comment]
georeferencing raster data is already available
