### ISSUE TITLE
Make plugin work for QGIS3

### ISSUE THREAD

**Issue by goatchurchprime** [patrickbwarren/qgis-survex-import#6]
Firstly, the new plugin directory is here:
    /home/USER/.local/share/QGIS/QGIS3/profiles/default/python/plugins

On the off-chance, I tried it and got plugin broken error in the plugin manager.  It's complaining of "Missing metadata file"

**Comment by goatchurchprime** [comment]
I was trying to get it working for the Imperial Slovenia data, but they're going to need to fix their coordinate system before it works:  https://github.com/jarvist/migovecsurveydata/issues/6

**Comment by patrickbwarren** [comment]
QGIS3 version at 
https://github.com/patrickbwarren/qgis3-survex-import

**Comment by patrickbwarren** [comment]
QGIS3 version at
https://github.com/patrickbwarren/qgis3-survex-import
This has instructions for installing in the QGIS3 user plugin directory
